package trabalho_urna;

import java.awt.Dimension;
import java.awt.GridBagLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;

public class PrincipalFrame extends javax.swing.JFrame {

    /**
     * ********************************************************************************************************************************
     */
    //VARIVEIS E INSTANCIAS
    Urna urna = new Urna();
    boolean bCadastra = true;
    boolean bVotoPrefeito = false;
    boolean bVota = true;

    /**
     * ********************************************************************************************************************************
     */
    public PrincipalFrame() {
        initComponents();

        centralizarContainer(inicialPanel);
        
        this.setSize(700, 700);
        this.setMinimumSize(new Dimension(700, 700));
        this.setMaximumSize(new Dimension(700, 700));

        SetVisible("TelaInicial");
    }

    /**
     * ********************************************************************************************************************************
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicialPanel = new javax.swing.JPanel();
        cadastroButton = new javax.swing.JButton();
        iniciarVotacaoButton = new javax.swing.JButton();
        encerrarButton = new javax.swing.JButton();
        cadastroPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cargoCandidatoComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        numeroCandidatoFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        salvarCandidatoButton = new javax.swing.JButton();
        cancelarCandidatoButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        nomeCandidatoFormattedTextField = new javax.swing.JTextField();
        partidoFormattedTextField = new javax.swing.JTextField();
        votacaoPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        votarButton = new javax.swing.JButton();
        cancelarVotacaoButton = new javax.swing.JButton();
        nomeCandidatoLabel = new javax.swing.JLabel();
        partidoCandidatoLabel = new javax.swing.JLabel();
        pesquisanumerocandidato = new javax.swing.JTextField();
        limparCandidatoButton = new javax.swing.JButton();
        nomeEleitor = new javax.swing.JTextField();
        numeroTitulo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tipoCandidatoLabel = new javax.swing.JLabel();
        resultadoVotacaoPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cadastroButton.setText("Cadastro Candidato");
        cadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroButtonActionPerformed(evt);
            }
        });

        iniciarVotacaoButton.setText("Iniciar Votação");
        iniciarVotacaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarVotacaoButtonActionPerformed(evt);
            }
        });

        encerrarButton.setText("Encerrar Votação");
        encerrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encerrarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inicialPanelLayout = new javax.swing.GroupLayout(inicialPanel);
        inicialPanel.setLayout(inicialPanelLayout);
        inicialPanelLayout.setHorizontalGroup(
            inicialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicialPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cadastroButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iniciarVotacaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(encerrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        inicialPanelLayout.setVerticalGroup(
            inicialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inicialPanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(inicialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cadastroButton)
                    .addComponent(iniciarVotacaoButton)
                    .addComponent(encerrarButton))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jLabel1.setText("Nome Candidato");

        cargoCandidatoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prefeito", "Vereador" }));

        jLabel2.setText("Cargo Candidato");

        jLabel3.setText("Número Candidato");

        salvarCandidatoButton.setText("Salvar");
        salvarCandidatoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarCandidatoButtonActionPerformed(evt);
            }
        });

        cancelarCandidatoButton.setText("Cancelar");
        cancelarCandidatoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCandidatoButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Sigla Partido");

        javax.swing.GroupLayout cadastroPanelLayout = new javax.swing.GroupLayout(cadastroPanel);
        cadastroPanel.setLayout(cadastroPanelLayout);
        cadastroPanelLayout.setHorizontalGroup(
            cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cadastroPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(salvarCandidatoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(cancelarCandidatoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cadastroPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(cadastroPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numeroCandidatoFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cargoCandidatoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, cadastroPanelLayout.createSequentialGroup()
                                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nomeCandidatoFormattedTextField)
                                    .addComponent(partidoFormattedTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))))
                        .addGap(54, 54, 54))))
        );
        cadastroPanelLayout.setVerticalGroup(
            cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cadastroPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomeCandidatoFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(partidoFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cargoCandidatoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroCandidatoFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(cadastroPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvarCandidatoButton)
                    .addComponent(cancelarCandidatoButton))
                .addGap(20, 20, 20))
        );

        jLabel5.setText("Nome Eleitor");

        jLabel6.setText("Número Título");

        jLabel7.setText("Número do Candidato");

        jLabel8.setText("Nome Candidato");

        jLabel9.setText("Partido Candidato");

        votarButton.setText("Confirmar");
        votarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                votarButtonActionPerformed(evt);
            }
        });

        cancelarVotacaoButton.setText("Cancelar Votação");
        cancelarVotacaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarVotacaoButtonActionPerformed(evt);
            }
        });

        pesquisanumerocandidato.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                pesquisanumerocandidatoFocusLost(evt);
            }
        });

        limparCandidatoButton.setText("Limpar Candidato");
        limparCandidatoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparCandidatoButtonActionPerformed(evt);
            }
        });

        numeroTitulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                numeroTituloFocusLost(evt);
            }
        });

        jLabel10.setText("Tipo do Candidato");

        javax.swing.GroupLayout votacaoPanelLayout = new javax.swing.GroupLayout(votacaoPanel);
        votacaoPanel.setLayout(votacaoPanelLayout);
        votacaoPanelLayout.setHorizontalGroup(
            votacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(votacaoPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(votacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(votacaoPanelLayout.createSequentialGroup()
                        .addGroup(votacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(votacaoPanelLayout.createSequentialGroup()
                                .addGroup(votacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGap(58, 58, 58)
                                .addGroup(votacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nomeEleitor)
                                    .addComponent(numeroTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                            .addGroup(votacaoPanelLayout.createSequentialGroup()
                                .addGroup(votacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(votacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, votacaoPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, votacaoPanelLayout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(41, 41, 41)))
                                    .addGroup(votacaoPanelLayout.createSequentialGroup()
                                        .addGroup(votacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGap(33, 33, 33)))
                                .addGroup(votacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nomeCandidatoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(partidoCandidatoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(pesquisanumerocandidato, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(tipoCandidatoLabel))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(votacaoPanelLayout.createSequentialGroup()
                        .addComponent(votarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limparCandidatoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelarVotacaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );
        votacaoPanelLayout.setVerticalGroup(
            votacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(votacaoPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(votacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nomeEleitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(votacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(numeroTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(votacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pesquisanumerocandidato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(votacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(nomeCandidatoLabel))
                .addGap(18, 18, 18)
                .addGroup(votacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(partidoCandidatoLabel))
                .addGap(18, 18, 18)
                .addGroup(votacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tipoCandidatoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(votacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(votarButton)
                    .addComponent(limparCandidatoButton)
                    .addComponent(cancelarVotacaoButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout resultadoVotacaoPanelLayout = new javax.swing.GroupLayout(resultadoVotacaoPanel);
        resultadoVotacaoPanel.setLayout(resultadoVotacaoPanelLayout);
        resultadoVotacaoPanelLayout.setHorizontalGroup(
            resultadoVotacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );
        resultadoVotacaoPanelLayout.setVerticalGroup(
            resultadoVotacaoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cadastroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(resultadoVotacaoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inicialPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(votacaoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inicialPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(resultadoVotacaoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cadastroPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(731, 731, 731)
                        .addComponent(votacaoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * ********************************************************************************************************************************
     */
    //SALVA CANDIDATO NA LISTA
    private void salvarCandidatoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarCandidatoButtonActionPerformed

        bCadastra = true;

        if (nomeCandidatoFormattedTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, informe o nome do candidato.", "Candidato", JOptionPane.WARNING_MESSAGE);
            bCadastra = false;
            return;
        }

        if (partidoFormattedTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, informe o partido do candidato.", "Candidato", JOptionPane.WARNING_MESSAGE);
            bCadastra = false;
            return;
        }

        if (numeroCandidatoFormattedTextField.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, informe o número do candidato.", "Candidato", JOptionPane.WARNING_MESSAGE);
            bCadastra = false;
            return;
        }

        //VERIFICA SE NUMERO JA EXISTE
        if (urna.VerificaNumeroCandidato(numeroCandidatoFormattedTextField.getText())) {
            JOptionPane.showMessageDialog(null, "Número do Candidato já cadastrado.", "Candidato", JOptionPane.WARNING_MESSAGE);
            bCadastra = false;
            return;
        }

        if (bCadastra) {

            urna.CadastroCandidatos(new Candidato(nomeCandidatoFormattedTextField.getText(),
                    partidoFormattedTextField.getText(),
                    numeroCandidatoFormattedTextField.getText(),
                    cargoCandidatoComboBox.getSelectedItem().toString()));

            nomeCandidatoFormattedTextField.setText("");
            partidoFormattedTextField.setText("");
            numeroCandidatoFormattedTextField.setText("");
            cargoCandidatoComboBox.setSelectedIndex(0);
            JOptionPane.showMessageDialog(null, "Candidato cadastrado com sucesso.", "Candidato", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_salvarCandidatoButtonActionPerformed

    //CANCELA CADASTRO DO CANDIDATO E RETORNA PARA TELA INICIAL
    private void cancelarCandidatoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCandidatoButtonActionPerformed
        SetVisible("CancelarTelaCadastro");
    }//GEN-LAST:event_cancelarCandidatoButtonActionPerformed

    //BOTAO PARA ENCERRAR VOTAÇÃO
    private void encerrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encerrarButtonActionPerformed

        SetVisible("ResultadoVotacao");

        Object[][] candidatosMatriz;
        String[] colunas = {"Nome Candidato", "Número Candidato", "Partido", "Tipo Candidato", "Total votos"};

        List<Candidato> _CandidatoList = urna.ResultadoEleicao("Prefeito");
        _CandidatoList.addAll(urna.ResultadoEleicao("Vereador"));
        
        candidatosMatriz = new Object[_CandidatoList.size()][5];
        for (int i = 0; i < _CandidatoList.size(); i++) {
            for (int j = 0; j < 5; j++) {
                switch (j) {
                    case 0:
                        candidatosMatriz[i][j] = _CandidatoList.get(i).getNomeCandidato();
                        break;

                    case 1:
                        candidatosMatriz[i][j] = _CandidatoList.get(i).getNumeroCandidato();
                        break;

                    case 2:
                        candidatosMatriz[i][j] = _CandidatoList.get(i).getPartidoCandidato();
                        break;

                    case 3:
                        candidatosMatriz[i][j] = _CandidatoList.get(i).getTipoCandidato();
                        break;

                    case 4:
                        candidatosMatriz[i][j] = Integer.toString(_CandidatoList.get(i).getNumeroVotos());
                        break;
                }
            }
        }

        JTable candidatosTable = new JTable(candidatosMatriz, colunas);
        candidatosTable.setMinimumSize(new Dimension(600,200));
        JTableHeader header = candidatosTable.getTableHeader();
        JScrollPane barra = new JScrollPane(candidatosTable);
        barra.setMinimumSize(new Dimension(600, 200));
        
        candidatosTable.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        getContentPane().add(barra);
        
        
    }//GEN-LAST:event_encerrarButtonActionPerformed

    //INICIA VOTAÇÃO
    private void iniciarVotacaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarVotacaoButtonActionPerformed
        SetVisible("IniciarVotacao");

        if (!bVotoPrefeito) {
            JOptionPane.showMessageDialog(null, "Por favor, vote no seu candidato a Vereador.", "Votação", JOptionPane.WARNING_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Por favor, vote no seu candidato a Prefeito.", "Votação", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_iniciarVotacaoButtonActionPerformed

    //BOTÃO PARA ABRIR A TELA DE CADASTRO DO CANDIDATO
    private void cadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroButtonActionPerformed
        SetVisible("BotaoCadastro");
    }//GEN-LAST:event_cadastroButtonActionPerformed

    //TELA PARA O ELEITOR VOTAR
    private void votarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_votarButtonActionPerformed

        bVota = true;
        //INCLUI VOTAÇÃO
        if (nomeEleitor.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Eleitor!!!!\n Por favor informe seu nome.", "Votação", JOptionPane.WARNING_MESSAGE);
            bVota = false;
            return;
        } else {

            if (numeroTitulo.getText().equals("")) {
                JOptionPane.showMessageDialog(null, nomeEleitor.getText() + ", por favor informe o seu número do título de eleitor", "Votação", JOptionPane.WARNING_MESSAGE);
                bVota = false;
                return;
            }
        }

        if (pesquisanumerocandidato.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Por favor, informe o número do seu candidato.", "Votação", JOptionPane.WARNING_MESSAGE);
            bVota = false;
            return;
        }

        if (bVota) {

            if (!bVotoPrefeito) {

                //CHAMA METODO PARA ADICIONAR VOTO PARA O CANDIDATO
                urna.VotaCandidato(pesquisanumerocandidato.getText());

                bVotoPrefeito = true;
                JOptionPane.showMessageDialog(null, "Por favor, vote no seu candidato a Prefeito", "Votação", JOptionPane.WARNING_MESSAGE);
                pesquisanumerocandidato.setText("");
                nomeCandidatoLabel.setText("");
                partidoCandidatoLabel.setText("");
                tipoCandidatoLabel.setText("");
                pesquisanumerocandidato.enable(true);

            } else {

                //CHAMA METODO PARA ADICIONAR VOTO PARA O CANDIDATO
                urna.VotaCandidato(pesquisanumerocandidato.getText());

                bVotoPrefeito = false;
                JOptionPane.showMessageDialog(null, "Votação concluida e contabilizada. Obrigado", "Votação", JOptionPane.WARNING_MESSAGE);
                LimpaCamposVotacao();
                SetVisible("FinalizaVotacao");
            }
        }
    }//GEN-LAST:event_votarButtonActionPerformed

    //BOTÃO PARA EFETUAR O CANCELAMENTO DA VOTAÇÃO E VOLTAR PARA TELA INICIAL
    private void cancelarVotacaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarVotacaoButtonActionPerformed
        SetVisible("CancelarVotacao");
        LimpaCamposVotacao();
    }//GEN-LAST:event_cancelarVotacaoButtonActionPerformed

    //EVENTO CHAMADO QUANDO O FOCO SAI DO CAMPO DE PESQUISA CANDIDATO PELO NUMERO
    //AO SAIR O FOCO DO CAMPO É CHAMADO O METODO DA CLASSE URNA PARA PESQUISAR O CANDIDATO E RETORNAR OS DADOS DELE.
    private void pesquisanumerocandidatoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pesquisanumerocandidatoFocusLost

        if (!pesquisanumerocandidato.getText().equals("")) {
            Candidato objCandidato = new Candidato();
            objCandidato = urna.RetornaCandidato(pesquisanumerocandidato.getText(), (bVotoPrefeito == true ? "Prefeito" : "Vereador"));

            if (objCandidato != null) {
                nomeCandidatoLabel.setText(objCandidato.getNomeCandidato());
                partidoCandidatoLabel.setText(objCandidato.getPartidoCandidato());
                tipoCandidatoLabel.setText(objCandidato.getTipoCandidato());
                pesquisanumerocandidato.enable(false);
            } else {
                nomeCandidatoLabel.setText("");
                partidoCandidatoLabel.setText("");
                pesquisanumerocandidato.setText("");
                tipoCandidatoLabel.setText("");
                pesquisanumerocandidato.enable(true);

                JOptionPane.showMessageDialog(null, "Candidato não cadastrado. Por favor, informe outro candidato", "Candidato", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_pesquisanumerocandidatoFocusLost

    //BOTÃO QUE LIMPA OS DADOS DO CANDIDATO QUE ESTIVER NA TELA DE VOTAÇÃO
    private void limparCandidatoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparCandidatoButtonActionPerformed

        pesquisanumerocandidato.setText("");
        nomeCandidatoLabel.setText("");
        partidoCandidatoLabel.setText("");
        tipoCandidatoLabel.setText("");
        pesquisanumerocandidato.enable(true);
    }//GEN-LAST:event_limparCandidatoButtonActionPerformed

    //AO TIRAR O CURSOR (FOCO) DO CAMPO DE PESQUISA PELO NUMERO
    //PREENCHE OS LABELS COM O NOME DO CANDIDATO, COM O PARTIDO E COM O TIPO DE CANDIDATO
    private void numeroTituloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numeroTituloFocusLost
        nomeEleitor.enable(false);
        numeroTitulo.enable(false);
    }//GEN-LAST:event_numeroTituloFocusLost

    /**
     * ********************************************************************************************************************************
     */
    //METODO PARA LIMPAR OS CAMPOS DE ELEITOR E CANDIDATO SELECIONADO PELO ELEITOR.
    private void LimpaCamposVotacao() {
        nomeEleitor.setText("");
        numeroTitulo.setText("");
        pesquisanumerocandidato.setText("");
        nomeCandidatoLabel.setText("");
        partidoCandidatoLabel.setText("");
        tipoCandidatoLabel.setText("");

        nomeEleitor.enable(true);
        numeroTitulo.enable(true);
        pesquisanumerocandidato.enable(true);
    }

    //METODO PARA CENTRALIZAR OS PANELS NO CENTRO DO JFRAME
    public void centralizarContainer(JPanel filho) {
        // obter dimensões do pai
        int larguraPai = this.getWidth();
        int alturaPai = this.getHeight();
        // obter dimensões do filho
        int larguraFilho = filho.getWidth();
        int alturaFilho = filho.getWidth();
        // calcular novas coordenadas do filho  
        int novoX = (larguraPai - larguraFilho);
        int novoY = (alturaPai - alturaFilho);
        // centralizar filho
        filho.getParent().setLayout(new GridBagLayout());
        filho.setSize(new Dimension(novoX, novoY));
        filho.repaint();
    }

    //METODO PARA OCULTAR E MOSTRAR OS PANELS DE ACORDO COM OS BOTOES SELECIONADOSS.
    private void SetVisible(String strTela) {
        switch (strTela) {
            case "TelaInicial":
            case "CancelarTelaCadastro":
            case "CancelarVotacao":
            case "FinalizaVotacao":
            case "BotaoVoltarResultadoVotacao":
                inicialPanel.setVisible(true);
                cadastroPanel.setVisible(false);
                votacaoPanel.setVisible(false);
                resultadoVotacaoPanel.setVisible(false);
                break;

            case "BotaoCadastro":
                cadastroPanel.setVisible(true);
                inicialPanel.setVisible(false);
                votacaoPanel.setVisible(false);
                break;

            case "IniciarVotacao":
                votacaoPanel.setVisible(true);
                inicialPanel.setVisible(false);
                cadastroPanel.setVisible(false);
                break;

            case "ResultadoVotacao":
                resultadoVotacaoPanel.setVisible(true);
                inicialPanel.setVisible(false);
                cadastroPanel.setVisible(false);
                votacaoPanel.setVisible(false);
                break;
        }
    }

    /**
     * ********************************************************************************************************************************
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastroButton;
    private javax.swing.JPanel cadastroPanel;
    private javax.swing.JButton cancelarCandidatoButton;
    private javax.swing.JButton cancelarVotacaoButton;
    private javax.swing.JComboBox<String> cargoCandidatoComboBox;
    private javax.swing.JButton encerrarButton;
    private javax.swing.JPanel inicialPanel;
    private javax.swing.JButton iniciarVotacaoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton limparCandidatoButton;
    private javax.swing.JTextField nomeCandidatoFormattedTextField;
    private javax.swing.JLabel nomeCandidatoLabel;
    private javax.swing.JTextField nomeEleitor;
    private javax.swing.JFormattedTextField numeroCandidatoFormattedTextField;
    private javax.swing.JTextField numeroTitulo;
    private javax.swing.JLabel partidoCandidatoLabel;
    private javax.swing.JTextField partidoFormattedTextField;
    private javax.swing.JTextField pesquisanumerocandidato;
    private javax.swing.JPanel resultadoVotacaoPanel;
    private javax.swing.JButton salvarCandidatoButton;
    private javax.swing.JLabel tipoCandidatoLabel;
    private javax.swing.JPanel votacaoPanel;
    private javax.swing.JButton votarButton;
    // End of variables declaration//GEN-END:variables
}
